-- SanghaviMart demo seed. Password hashes are Argon2id placeholders.
-- Replace with real hashes generated by PasswordUtil::Hash in production.
-- Demo password for all accounts: password123 (rotate immediately).
INSERT INTO users (id, name, email, password_hash, role) VALUES
(1, 'Site Administrator', 'admin@sanghavimart.com', '$argon2id$v=19$m=65536,t=3,p=4$demo-admin', 'ADMIN'),
(2, 'Apex Electronics', 'seller.apex@sanghavimart.com', '$argon2id$v=19$m=65536,t=3,p=4$demo-seller', 'SELLER'),
(3, 'Neha Sanghavi', 'neha@sanghavimart.com', '$argon2id$v=19$m=65536,t=3,p=4$demo-buyer', 'BUYER')
ON CONFLICT (id) DO NOTHING;

INSERT INTO products (id, seller_id, name, description, price_cents, stock_qty, category, image_url) VALUES
(1, 2, 'NoisePulse ANC Headphones', 'Hybrid ANC wireless headphones.', 7999, 15, 'Electronics', ''),
(2, 2, 'UltraBook Pro 14', 'Dev-tuned laptop.', 109900, 6, 'Electronics', ''),
(3, 2, 'Precision Mechanical Keyboard', 'Hot-swappable keyboard.', 8950, 18, 'Electronics', '')
ON CONFLICT (id) DO NOTHING;
SELECT setval('users_id_seq', (SELECT max(id) FROM users));
SELECT setval('products_id_seq', (SELECT max(id) FROM products));
